name: Build, Push, and Deploy

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SERVER }}
          script: |
            echo "Testing SSH connection..." 
            echo "Success! File created by GitHub Actions." > /tmp/github-actions-test.txt
            cat /tmp/github-actions-test.txt
