name: Build, Push, and Deploy

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SERVER }}
          script: |
            # Pull the new image (replace 'myapp' with your image name)
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
            # Stop and remove the old container
            docker stop myapp || true
            docker rm myapp || true
            # Run the new container (adjust ports/volumes as needed)
            docker run -d --name myapp -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
