name: Test SSH Connection

on:
  workflow_dispatch:  # Allows manual triggering via GitHub UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (not strictly needed, but ensures the action runs)
        uses: actions/checkout@v4

      - name: SSH into Server and Create Test File
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SERVER }}
          script: |
            echo "Testing SSH connection..." 
            echo "Success! This file was created by GitHub Actions." > /tmp/github-actions-test.txt
            echo "Current date: $(date)" >> /tmp/github-actions-test.txt
            cat /tmp/github-actions-test.txt  # Print the file contents to the logs
