name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Server and Create Test File
        uses: appleboy/ssh-action@d0d6a0e8d8a1b3a3d8e0d4b4e0d4b4e0d4b4e0d4  # Use a commit SHA or newer tag
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SERVER }}
          script: |
            echo "Testing SSH connection..." 
            echo "Success! File created by GitHub Actions." > /tmp/github-actions-test.txt
            cat /tmp/github-actions-test.txt
            
